{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "11898615-38ab-40b9-b321-c39f20732d85",
   "metadata": {},
   "source": [
    "# Example Campaign Analysis\n",
    "\n",
    "This example is intended to demonstrate implementation of the Contextualize Trend Analysis dashboard using the HTMDEC DMS API. This example uses [Plotly Dash](https://dash.plotly.com/) to create a dynamic visualization of the Campaign dataframe. Note that data is only complete for `AAA` and `AAB`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "45e44dae-562c-4289-828b-5711a34a64bf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://localhost:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x126f363e0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "<dash.dash.Dash at 0x106173e50>"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2025-03-24 18:41:32,792] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 154, in update_dropdown_columns\n",
      "    defaults = [cols[i] if len(cols) > i else cols[0] for i in range(4)]\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 154, in <listcomp>\n",
      "    defaults = [cols[i] if len(cols) > i else cols[0] for i in range(4)]\n",
      "IndexError: list index out of range\n",
      "[2025-03-24 18:41:32,799] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2479, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1727, in build_dataframe\n",
      "    df_output, wide_id_vars = process_args_into_dataframe(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1328, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: Elastic Modulus.a\n",
      "[2025-03-24 18:41:36,157] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2479, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1727, in build_dataframe\n",
      "    df_output, wide_id_vars = process_args_into_dataframe(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1328, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: Elongation.a\n",
      "[2025-03-24 18:41:40,316] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2479, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1727, in build_dataframe\n",
      "    df_output, wide_id_vars = process_args_into_dataframe(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1328, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: Elongation.a\n",
      "[2025-03-24 18:41:44,320] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2479, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1727, in build_dataframe\n",
      "    df_output, wide_id_vars = process_args_into_dataframe(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1328, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: Elongation.a\n",
      "[2025-03-24 18:41:49,343] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2479, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1727, in build_dataframe\n",
      "    df_output, wide_id_vars = process_args_into_dataframe(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1328, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: Maximum ∂2σ/∂ε2.a\n",
      "[2025-03-24 18:41:52,278] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2479, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1727, in build_dataframe\n",
      "    df_output, wide_id_vars = process_args_into_dataframe(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 1328, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: Elastic Modulus.a\n",
      "[2025-03-24 18:43:40,922] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:43:44,642] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:43:48,666] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:43:52,261] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan, nan, nan, nan, nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:43:59,990] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan, nan, nan, nan, nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:44:06,386] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan, nan, nan, nan, nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:44:13,052] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan, nan, nan, nan, nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:44:16,521] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan, nan, nan, nan, nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:44:28,121] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan, nan, nan, nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:44:31,561] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:44:36,343] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan, nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:45:21,107] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:45:39,751] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:46:12,918] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:46:18,177] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n",
      "[2025-03-24 18:46:20,809] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/dash.py\", line 1405, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 529, in add_context\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 518, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/dash/_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/elbert/Documents/GitHub/htmdec/birdshot_dms_api/birdshot.py\", line 168, in update_graph\n",
      "    fig = px.scatter(df, x=x_col, y=y_col, color=color_col, size=size_col)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_chart_types.py\", line 69, in scatter\n",
      "    return make_figure(args=locals(), constructor=go.Scatter)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/express/_core.py\", line 2673, in make_figure\n",
      "    trace.update(patch)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5125, in update\n",
      "    BaseFigure._perform_update(self, dict1, overwrite=overwrite)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3905, in _perform_update\n",
      "    BaseFigure._perform_update(plotly_obj[key], val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 3926, in _perform_update\n",
      "    plotly_obj[key] = val\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 4860, in __setitem__\n",
      "    self._set_prop(prop, value)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5204, in _set_prop\n",
      "    raise err\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 5199, in _set_prop\n",
      "    val = validator.validate_coerce(val)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 784, in validate_coerce\n",
      "    self.raise_invalid_elements(some_invalid_els)\n",
      "  File \"/Users/elbert/miniconda3/envs/birdshot_api/lib/python3.10/site-packages/_plotly_utils/basevalidators.py\", line 315, in raise_invalid_elements\n",
      "    raise ValueError(\n",
      "ValueError: \n",
      "    Invalid element(s) received for the 'size' property of scatter.marker\n",
      "        Invalid elements include: [nan]\n",
      "\n",
      "    The 'size' property is a number and may be specified as:\n",
      "      - An int or float in the interval [0, inf]\n",
      "      - A tuple, list, or one-dimensional numpy array of the above\n"
     ]
    }
   ],
   "source": [
    "import birdshot\n",
    "birdshot.show_plot()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8eba5b2a-85ed-4da0-8576-e8494baf24a4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (birdshot_api)",
   "language": "python",
   "name": "birdshot_api"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
